# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - 'AUTHORS'
      - 'LICENSE'
      - 'NOTICE'
      - '**.md'
      - '.gitignore'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main
      - master

jobs:
  test:
    name: Unit Tests
    runs-on: [ ubuntu-20.04 ]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Install the dependent packages
      - name: Install packages
        run: |
          sudo apt update
          sudo apt-get -y install valgrind libcunit1 libcunit1-doc libcunit1-dev libcurl4-openssl-dev openssl libexpat1-dev gcovr
          pip install codecov

      - name: Make Build Directory
        run: mkdir build

      - name: Get Sonarcloud Binaries
        uses: xmidt-org/sonarcloud-installer-action@v1
        with:
          working-directory: build

      - name: Get rtrouted  Binary
        working-directory: build
        run: |
          ../.github/scripts/rtrouted.sh          

      - name: CMake
        working-directory: build
        run: |
          cmake .. -DBUILD_TESTING:BOOL=true -DBUILD_GIT:BOOL=true

      - name: Build
        working-directory: build
        run: |
          ps aux 
          export RBUS_ROOT=${HOME}/rbus
          export RBUS_INSTALL_DIR=${RBUS_ROOT}/install && \
          export LD_LIBRARY_PATH=${RBUS_INSTALL_DIR}/usr/lib/rbus_temp_lib:${LD_LIBRARY_PATH}            
          export C_INCLUDE_PATH=${RBUS_INSTALL_DIR}/usr/include                   
          mkdir _install
          mkdir _install/lib
          cp ${RBUS_INSTALL_DIR}/usr/lib/librbus* _install/lib        
          build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output make all

      - name: Test
        working-directory: build
        run: |
          # ARGS=-VV make test       # use this version for debugging
          make test

      - name: Merge GCOV Reports for Sonarcloud
        working-directory: build
        run: |
          gcovr --sonarqube coverage.xml -r ..

      # - name: Upload SonarCloud
      #   run: |
      #     build/sonar-scanner/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dproject.settings=.sonar-project.properties -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Codecov.io
        uses: codecov/codecov-action@v1
        with:
          directory: .
          fail_ci_if_error: true
